spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pricetracker
    username: postgres
    password: CHANGE_ME
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: CHANGE_ME_GENERATE_256BIT_HEX
      expiration: 86400000

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR