spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/pricetracker
    username: postgres
    password: post123
  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

server:
  port: 8080

application:
  security:
    jwt:
      secret-key: 1FD663A6D3B3808E5360594DE0BDEEA40CCA071D10B06A7AD3F98100A69487A0
      expiration: 86400000

logging:
  level:
    org.springframework.security.config.annotation.authentication.configuration.InitializeUserDetailsBeanManagerConfigurer: ERROR